# Generated by Django 5.2.3 on 2025-07-06 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookingapp', '0003_groceryitem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GroceryItem',
        ),
        migrations.AddField(
            model_name='contactmsg',
            name='contact_msg',
            field=models.CharField(default='Not provided', max_length=255),
            preserve_default=False,
        ),
    ]
