# Generated by Django 5.2.3 on 2025-07-08 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookingapp', '0005_room_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='password',
            field=models.TextField(max_length=100),
        ),
    ]
