# Generated by Django 5.2.3 on 2025-07-09 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookingapp', '0006_alter_useraccount_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='room_booking',
            name='room_title',
            field=models.CharField(default='Unknown room', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contactmsg',
            name='contact_msg',
            field=models.TextField(max_length=255),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='password',
            field=models.CharField(max_length=100),
        ),
    ]
