# Generated by Django 5.2.3 on 2025-07-09 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookingapp', '0007_room_booking_room_title_alter_contactmsg_contact_msg_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='room_booking',
            name='room_capacity',
            field=models.CharField(default='Not Known', max_length=200),
            preserve_default=False,
        ),
    ]
